[package]
name = "gitit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
enigo = "0.1.2"
ratatui = { version = "0.22.0", features = ["all-widgets"] }
regex = "1.9.3"
